# Generated by Django 5.0.4 on 2024-04-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_story_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
