# Generated by Django 5.0.4 on 2024-04-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_story_user_alter_story_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='title_single',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='', max_length=400),
        ),
    ]
