# Generated by Django 5.0.4 on 2024-04-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_story_author_story_description_story_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
