# Generated by Django 5.0.4 on 2024-04-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_story_content_story_urltoimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='bookmarked_by',
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='home.story')),
            ],
        ),
    ]
