# Generated by Django 5.0.4 on 2024-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_request_hour',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requests_this_hour',
            field=models.IntegerField(default=0),
        ),
    ]
